# Generated by Django 4.0.4 on 2022-04-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_fist_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_last_na_e6a359_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
